#!/usr/bin/env python3
"""Helper for the youtrack-prioritize-youtrack-tickets skill.

The deterministic pieces of a backlog refinement, so the agent running the skill
does not improvise pagination, eligibility, payloads or retries. Judgement
(dependencies read out of prose, urgency, ranking, which host a ticket is about)
stays with the agent and reaches this helper as a plan file.

Offline subcommands (no credentials, run with plain python3):
  validate-plan SNAPSHOT PLAN    check a plan against the snapshot it was made from
  review-table SNAPSHOT PLAN [--batch-size N]
                                 the review table to show the human
  render-section SNAPSHOT PLAN   preview the generated epic section

API subcommands (run through ./yt-backlog, which wraps them in
`parzival exec --as ai youtrack-claude-code`):
  resolve-project PROJECT        one live project by short name, id, URL or exact name
  collect PROJECT OUT            read-only snapshot of the whole project to JSON
  read-issue ISSUE               read-only: one issue in any project, with links and comments
  apply SNAPSHOT PLAN --journal FILE [--dry-run]
                                 recheck live state, then apply only what the plan
                                 approves, verifying every write by reading it back

Nothing is written during resolve-project, collect or read-issue. apply is the
only subcommand that writes, and --dry-run lists its operations without writing.

Open backlog means Status is neither Done nor the do-not-do value. It is decided
from the Status field itself, never from `resolved`: on this instance a set
Category keeps a Done issue unresolved, and `Wont do` is not a resolved state
(~/Projects/private/youtrack.kevininscoe.com/reference/custom-fields.md).

The token never passes through this script: API calls shell out to curl with
-K "$YOUTRACK_CURL_CONFIG", the RAM-backed config parzival renders for its
child process (when-creating-a-youtrack-ticket.md section 14).
"""

import argparse
import datetime
import json
import os
import re
import subprocess
import sys
import time
import urllib.parse

BASE_URL = os.environ.get("YOUTRACK_API_URL", "http://127.0.0.1:9000")
PUBLIC_URL = "https://youtrack.kevininscoe.com"

PAGE_SIZE = 100  # the server may cap $top; never infer the end from a short page
SHORT_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")

EPIC_SUFFIX = "-backlog-refinement"
EPIC_TYPE = "Epic"

# Fields are found on a live issue by name. The prototype ID is only a cross-check
# that the field carrying that name is the one this instance means by it (there
# is a second, unattached `State` prototype one character away from `Status`).
# A mismatch stops the run for a human instead of guessing.
FIELDS = {
    "status": ("Status", "157-2"),
    "priority": ("Priority", "157-0"),
    "type": ("Type", "157-1"),
    "assignee": ("Assignee", "157-3"),
    "affected_host": ("Affected host", "157-32"),
    "date_entered": ("Date time entered", "157-15"),
}

ALLOWED_PRIORITIES = ("Show-stopper", "Critical", "Major", "Normal", "Minor")
DONE = "done"
DO_NOT_DO = ("wontdo", "dontdo", "donotdo", "willnotdo")

READINESS = ("ready", "blocked", "needs-clarification")
FIELD_DECISIONS = ("approved", "rejected", "pending", "unchanged")

BEGIN_PREFIX = "[backlog-refinement:begin]"
END_MARK = "[backlog-refinement:end]"
BEGIN_LINE = (f"{BEGIN_PREFIX} Generated by the youtrack-prioritize-youtrack-tickets skill. "
              "This section is replaced on every run; write your own notes outside it.")

LIST_FIELDS = (
    "id,idReadable,summary,description,created,updated,resolved,project(id,shortName),"
    "customFields(id,name,$type,projectCustomField(field(id)),value(name,login)),"
    "parent(issues(id,idReadable,summary,project(shortName)))"
)
BUNDLE_FIELDS = "customFields(name,projectCustomField(field(id),bundle(values(name,archived))))"
LINK_FIELDS = ("id,direction,linkType(id,name,sourceToTarget,targetToSource,directed,aggregation),"
               "issues(id)")
LINKED_ISSUE_FIELDS = ("id,idReadable,summary,project(shortName),"
                       "customFields(name,projectCustomField(field(id)),value(name))")
COMMENT_FIELDS = "id,text,created,deleted,author(login)"


class Fail(Exception):
    """A refusal or an API failure. Reported, never worked around."""


def norm(name):
    return re.sub(r"[^a-z0-9]", "", (name or "").lower())


def issue_url(readable):
    return f"{PUBLIC_URL}/issue/{readable}"


# ---------------------------------------------------------------- API layer

def api(method, path, params=None, body=None):
    cfg = os.environ.get("YOUTRACK_CURL_CONFIG")
    if not cfg:
        raise Fail("YOUTRACK_CURL_CONFIG is not set: run API subcommands through ./yt-backlog")
    url = f"{BASE_URL}{path}"
    if params:
        url += "?" + urllib.parse.urlencode(params, safe="(),$")
    cmd = ["curl", "-sS", "--max-time", "60", "-K", cfg, "-H", "Accept: application/json",
           "-X", method, "-w", "\n%{http_code}", url]
    data = None
    if body is not None:
        cmd[1:1] = ["-H", "Content-Type: application/json", "--data-binary", "@-"]
        data = json.dumps(body)
    proc = subprocess.run(cmd, input=data, capture_output=True, text=True)
    if proc.returncode != 0:
        raise Fail(f"curl failed ({proc.returncode}): {proc.stderr.strip()}")
    payload, _, status = proc.stdout.rpartition("\n")
    if not status.isdigit() or int(status) >= 300:
        raise Fail(f"{method} {path} -> HTTP {status}: {payload[:400]}")
    return json.loads(payload) if payload.strip() else None


def paginate(fetch):
    """Call fetch(skip, top) until an empty page. Never stops on a short page,
    because the server may cap $top; refuses to loop on a pager that stalls."""
    out, skip, seen_first = [], 0, set()
    while True:
        batch = fetch(skip, PAGE_SIZE)
        if not batch:
            return out
        first = json.dumps(batch[0], sort_keys=True)
        if first in seen_first:
            raise Fail(f"pager stalled at offset {skip}: the same page came back twice")
        seen_first.add(first)
        out.extend(batch)
        skip += len(batch)


def api_list(path, fields, extra=None):
    def fetch(skip, top):
        params = {"fields": fields, "$top": top, "$skip": skip}
        params.update(extra or {})
        return api("GET", path, params)
    return paginate(fetch)


# ------------------------------------------------------------ project, fields

def resolve_project(raw):
    """Exactly one live project, or a Fail that lists the candidates."""
    value = raw.strip()
    if "/projects/" in value:
        value = value.split("/projects/", 1)[1].split("/")[0].split("?")[0]
    projects = api_list("/api/admin/projects", "id,shortName,name")
    low = value.lower()
    exact = [p for p in projects
             if p["id"] == value or p["shortName"].lower() == low or p["name"].lower() == low]
    if len(exact) == 1:
        project = exact[0]
    else:
        near = exact or [p for p in projects
                         if low in p["name"].lower() or low in p["shortName"].lower()]
        listing = ", ".join(f"{p['shortName']} ({p['name']})" for p in near) or "none"
        raise Fail(f"{raw!r} does not name exactly one project visible to Claude_Code. "
                   f"Candidates: {listing}")
    short = project["shortName"]
    if not SHORT_NAME_RE.match(short):
        raise Fail(f"unexpected project short name {short!r}")
    # The Claude_Code token is not shown a project's `template` flag, so fail
    # closed on the name: an issue filed in a template project cannot be edited,
    # found or removed again (when-creating-a-youtrack-ticket.md section 1).
    if short.upper() == "TMPL" or "template" in project["name"].lower():
        raise Fail(f"{short} is a template project; this skill never writes there")
    return project


def field_map(issue):
    """key -> the issue's own custom field, found by name and confirmed by prototype."""
    out = {}
    for key, (name, proto) in FIELDS.items():
        named = [f for f in issue.get("customFields", []) if f.get("name") == name]
        if not named:
            continue
        if len(named) > 1:
            raise Fail(f"{issue.get('idReadable')} carries {len(named)} fields named {name!r}; "
                       "a human must say which one is meant")
        found = ((named[0].get("projectCustomField") or {}).get("field") or {}).get("id")
        if found != proto:
            raise Fail(f"the field named {name!r} has prototype {found}, not the expected "
                       f"{proto}. The schema changed: confirm which field is {name} before "
                       "this skill reads or writes it")
        out[key] = named[0]
    return out


def field_value(issue, key):
    fld = field_map(issue).get(key)
    value = (fld or {}).get("value")
    if isinstance(value, dict):
        return value.get("name") or value.get("login")
    return value


def read_bundles(issue_id):
    """Live allowed values for Status, Priority, Type and Affected host."""
    issue = api("GET", f"/api/issues/{issue_id}", {"fields": BUNDLE_FIELDS})
    out = {}
    for key, (name, proto) in FIELDS.items():
        for f in issue.get("customFields", []):
            pcf = f.get("projectCustomField") or {}
            if f.get("name") == name and (pcf.get("field") or {}).get("id") == proto:
                values = (pcf.get("bundle") or {}).get("values")
                if values is not None:
                    out[key] = [v["name"] for v in values if not v.get("archived")]
    for key in ("status", "priority", "type", "affected_host"):
        if not out.get(key):
            raise Fail(f"could not read the live values of {FIELDS[key][0]}; "
                       "treating that as a gap, not as an empty list")
    return out


def status_mapping(statuses):
    done = [s for s in statuses if norm(s) == DONE]
    dnd = [s for s in statuses if norm(s) in DO_NOT_DO]
    if not done:
        raise Fail(f"no Done value among the live Status values: {statuses}")
    note = (f"Open means Status is not {', '.join(done + dnd)}. "
            + ("" if dnd else "No do-not-do Status value exists on this instance. ")
            + "Status is read from the field itself, never from the resolved flag.")
    return {"done": done, "do_not_do": dnd, "excluded": done + dnd, "rule": note}


def status_class(status, mapping):
    if not status:
        return "unknown"
    if status in mapping["done"]:
        return "done"
    if status in mapping["do_not_do"]:
        return "do-not-do"
    return "open"


# ------------------------------------------------------------------ link types

def link_types():
    types = api_list("/api/issueLinkTypes",
                     "id,name,sourceToTarget,targetToSource,directed,aggregation")
    subtask = [t for t in types if t.get("directed") and t.get("aggregation")
               and norm(t.get("targetToSource")) == "subtaskof"]
    depend = [t for t in types if t.get("directed") and not t.get("aggregation")
              and norm(t.get("targetToSource")) == "dependson"]
    return {"subtask": subtask[0] if len(subtask) == 1 else None,
            "depend": depend[0] if len(depend) == 1 else None,
            "all": types}


def subtask_link_id(epic_id, types):
    """The epic's own outward 'parent for' link, read from the instance."""
    if not types["subtask"]:
        raise Fail("could not identify exactly one parent/subtask link type on this instance")
    links = api_list(f"/api/issues/{epic_id}/links", "id,direction,linkType(id)")
    mine = [link for link in links if link["linkType"]["id"] == types["subtask"]["id"]
            and link["direction"] == "OUTWARD"]
    if len(mine) != 1:
        raise Fail("the epic does not expose exactly one outward parent/subtask link")
    return mine[0]["id"]


# --------------------------------------------------------------------- collect

def parent_of(issue):
    issues = ((issue.get("parent") or {}).get("issues")) or []
    return issues[0] if issues else None


def read_project_issues(short):
    issues = api_list("/api/issues", LIST_FIELDS, {"query": f"project: {short}"})
    seen, out, strays = set(), [], []
    for i in issues:
        if i["id"] in seen:
            continue
        seen.add(i["id"])
        if (i.get("project") or {}).get("shortName") != short:
            strays.append(i.get("idReadable"))
            continue
        out.append(i)
    return out, strays


def read_links(issue_id):
    """Every link of one issue, with each side paginated on its own."""
    out = []
    for link in api_list(f"/api/issues/{issue_id}/links", LINK_FIELDS):
        if not link.get("issues"):
            continue
        linked = api_list(f"/api/issues/{issue_id}/links/{link['id']}/issues", LINKED_ISSUE_FIELDS)
        lt = link["linkType"]
        role = (lt.get("sourceToTarget") if link["direction"] in ("OUTWARD", "BOTH")
                else lt.get("targetToSource")) or lt.get("name")
        for other in linked:
            status = None
            for f in other.get("customFields", []):
                if f.get("name") == FIELDS["status"][0] and isinstance(f.get("value"), dict):
                    status = f["value"].get("name")
            out.append({"type": lt.get("name"), "type_id": lt.get("id"),
                        "direction": link["direction"], "role": role,
                        "issue": other.get("idReadable"), "id": other.get("id"),
                        "summary": other.get("summary"),
                        "project": (other.get("project") or {}).get("shortName"),
                        "status": status})
    return out


def read_comments(issue_id):
    return [{"id": c["id"], "author": (c.get("author") or {}).get("login"),
             "created": c.get("created"), "text": c.get("text") or ""}
            for c in api_list(f"/api/issues/{issue_id}/comments", COMMENT_FIELDS)
            if not c.get("deleted")]


def shape_issue(raw, mapping, epic_summary):
    status = field_value(raw, "status")
    cls = status_class(status, mapping)
    is_epic = (raw.get("summary") or "") == epic_summary
    parent = parent_of(raw)
    return {
        "id": raw["id"], "idReadable": raw["idReadable"], "url": issue_url(raw["idReadable"]),
        "summary": raw.get("summary") or "", "description": raw.get("description") or "",
        "created": raw.get("created"), "updated": raw.get("updated"),
        # Recorded so a reader can see it disagree with Status. Never used to decide.
        "resolved_flag": raw.get("resolved") is not None,
        "status": status, "status_class": cls,
        "priority": field_value(raw, "priority"), "type": field_value(raw, "type"),
        "affected_host": field_value(raw, "affected_host"),
        "is_epic_candidate": is_epic,
        "eligible": cls == "open" and not is_epic,
        "parent": ({"id": parent["id"], "idReadable": parent.get("idReadable"),
                    "summary": parent.get("summary"),
                    "project": (parent.get("project") or {}).get("shortName")}
                   if parent else None),
    }


def now_stamp():
    return datetime.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M %Z (UTC%z)")


def collect(project, deep=True):
    """Read-only snapshot of a project. deep=False skips links and comments."""
    short = project["shortName"]
    raw, strays = read_project_issues(short)
    if not raw:
        raise Fail(f"search finds no issue in {short}. It is empty or a template project; "
                   "there is no backlog to refine and no live issue to read the schema from")
    field_map(raw[0])  # confirm Status is really Status before anything is classified
    bundles = read_bundles(raw[0]["id"])
    mapping = status_mapping(bundles["status"])
    types = link_types()
    epic_summary = f"{short}{EPIC_SUFFIX}"
    gaps = [{"issue": s, "what": "returned by the project search but belongs to another project"}
            for s in strays]
    issues = []
    for r in raw:
        issue = shape_issue(r, mapping, epic_summary)
        if deep and (issue["eligible"] or issue["status_class"] == "unknown"
                     or issue["is_epic_candidate"]):
            for what, reader in (("links", read_links), ("comments", read_comments)):
                try:
                    issue[what] = reader(issue["id"])
                except Fail as exc:
                    issue[what] = None  # unread, which is not the same as empty
                    gaps.append({"issue": issue["idReadable"], "what": what, "error": str(exc)})
        issues.append(issue)
    issues.sort(key=lambda i: issue_number(i["idReadable"]))

    candidates = []
    for i in issues:
        if not i["is_epic_candidate"]:
            continue
        cand = {"id": i["id"], "idReadable": i["idReadable"], "type": i["type"],
                "status": i["status"], "status_class": i["status_class"],
                "description": i["description"]}
        try:
            cand["previous_ranks"] = previous_ranks(i["description"])
            cand["section"] = section_state(i["description"])
        except Fail as exc:
            cand["previous_ranks"], cand["section"] = {}, f"malformed: {exc}"
        try:
            cand["children"] = read_children(i["id"], types, mapping)
        except Fail as exc:
            cand["children"] = None
            gaps.append({"issue": i["idReadable"], "what": "children", "error": str(exc)})
        candidates.append(cand)

    snap = {
        "project": {"id": project["id"], "shortName": short, "name": project.get("name")},
        "collected_at": now_stamp(), "epic_summary": epic_summary,
        "bundles": bundles, "status_mapping": mapping,
        "link_types": {"subtask": types["subtask"], "depend": types["depend"]},
        "issues": issues, "epic_candidates": candidates, "gaps": gaps,
    }
    snap["analysis"] = analyse(snap)
    return snap


def read_children(epic_id, types, mapping):
    link_id = subtask_link_id(epic_id, types)
    out = []
    for c in api_list(f"/api/issues/{epic_id}/links/{link_id}/issues", LINKED_ISSUE_FIELDS):
        status = None
        for f in c.get("customFields", []):
            if f.get("name") == FIELDS["status"][0] and isinstance(f.get("value"), dict):
                status = f["value"].get("name")
        out.append({"id": c["id"], "idReadable": c.get("idReadable"),
                    "project": (c.get("project") or {}).get("shortName"),
                    "status": status, "status_class": status_class(status, mapping)})
    return out


def issue_number(readable):
    head, _, tail = (readable or "").rpartition("-")
    return (head, int(tail) if tail.isdigit() else 0)


# -------------------------------------------------------------------- analysis

def dependency_edges(snap):
    """Explicit dependency links only: (dependent, prerequisite, link record).

    A 'relates to' link is not a dependency and never becomes an edge here.
    """
    depend = snap["link_types"].get("depend")
    edges = {}
    if not depend:
        return []
    for i in snap["issues"]:
        for link in i.get("links") or []:
            if link["type_id"] != depend["id"]:
                continue
            if link["direction"] == "INWARD":      # this issue depends on the other
                edges.setdefault((i["idReadable"], link["issue"]), link)
            elif link["direction"] == "OUTWARD":   # this issue is required for the other
                edges.setdefault((link["issue"], i["idReadable"]),
                                 {"project": snap["project"]["shortName"], "status": i["status"],
                                  "summary": i["summary"]})
    return [(a, b, rec) for (a, b), rec in sorted(edges.items())]


def find_cycles(pairs):
    """Strongly connected components of size > 1 (and self-loops), sorted."""
    graph = {}
    for a, b in pairs:
        graph.setdefault(a, set()).add(b)
        graph.setdefault(b, set())
    index, low, on, stack, out, counter = {}, {}, set(), [], [], [0]

    def visit(v):
        index[v] = low[v] = counter[0]
        counter[0] += 1
        stack.append(v)
        on.add(v)
        for w in sorted(graph[v]):
            if w not in index:
                visit(w)
                low[v] = min(low[v], low[w])
            elif w in on:
                low[v] = min(low[v], index[w])
        if low[v] == index[v]:
            comp = []
            while True:
                w = stack.pop()
                on.discard(w)
                comp.append(w)
                if w == v:
                    break
            if len(comp) > 1 or v in graph[v]:
                out.append(sorted(comp, key=issue_number))

    for v in sorted(graph):
        if v not in index:
            visit(v)
    return sorted(out)


def analyse(snap):
    short = snap["project"]["shortName"]
    mapping = snap["status_mapping"]
    by_id = {i["idReadable"]: i for i in snap["issues"]}
    eligible = [i["idReadable"] for i in snap["issues"] if i["eligible"]]
    epic_ids = {c["idReadable"] for c in snap["epic_candidates"]}
    deps = []
    for a, b, rec in dependency_edges(snap):
        blocker = by_id.get(b)
        project = blocker and short or rec.get("project")
        status = blocker["status"] if blocker else rec.get("status")
        cls = status_class(status, mapping) if status else "unknown"
        deps.append({"issue": a, "depends_on": b, "blocker_project": project,
                     "blocker_status": status, "blocker_class": cls,
                     "cross_project": project != short,
                     # A do-not-do prerequisite is not thereby satisfied.
                     "note": ("prerequisite will not be done: the dependent needs an "
                              "alternative or a scope change" if cls == "do-not-do" else "")})
    return {
        "counts": {"issues": len(snap["issues"]), "eligible": len(eligible),
                   "excluded": sum(1 for i in snap["issues"]
                                   if i["status_class"] in ("done", "do-not-do")),
                   "status_unknown": sum(1 for i in snap["issues"]
                                         if i["status_class"] == "unknown")},
        "eligible": eligible,
        "status_unknown": [i["idReadable"] for i in snap["issues"]
                           if i["status_class"] == "unknown"],
        "resolved_flag_disagrees": [i["idReadable"] for i in snap["issues"]
                                    if i["resolved_flag"] != (i["status_class"] != "open")
                                    and i["status_class"] != "unknown"],
        "dependencies": deps,
        "cross_project_blockers": [d for d in deps if d["cross_project"]],
        "cycles": find_cycles([(d["issue"], d["depends_on"]) for d in deps]),
        "parent_conflicts": [{"issue": i["idReadable"], "parent": i["parent"]["idReadable"],
                              "parent_project": i["parent"]["project"]}
                             for i in snap["issues"]
                             if i["eligible"] and i["parent"]
                             and i["parent"]["idReadable"] not in epic_ids],
        "epic_state": {0: "none", 1: "one"}.get(len(snap["epic_candidates"]), "multiple"),
        "incomplete_reads": len(snap["gaps"]),
    }


# ------------------------------------------------------- generated epic section

def _marker_lines(description):
    lines = (description or "").replace("\r\n", "\n").split("\n")
    begins = [n for n, line in enumerate(lines) if line.strip().startswith(BEGIN_PREFIX)]
    ends = [n for n, line in enumerate(lines) if line.strip() == END_MARK]
    return lines, begins, ends


def section_state(description):
    """'none' or 'one'. Raises Fail when the markers are malformed or duplicated."""
    _, begins, ends = _marker_lines(description)
    if not begins and not ends:
        return "none"
    if len(begins) != 1 or len(ends) != 1 or begins[0] > ends[0]:
        raise Fail(f"the epic description holds {len(begins)} begin and {len(ends)} end "
                   "generated-section markers. Exactly one ordered pair is required: fix the "
                   "description by hand, nothing was written")
    return "one"


def splice_section(description, section):
    """Replace the generated section, or append one. Text outside it is untouched."""
    lines, begins, ends = _marker_lines(description)
    if section_state(description) == "none":
        body = "\n".join(lines).rstrip("\n")
        return (body + "\n\n" if body.strip() else "") + section
    return "\n".join(lines[:begins[0]] + section.split("\n") + lines[ends[0] + 1:])


def outside_section(description):
    lines, begins, ends = _marker_lines(description)
    if section_state(description) == "none":
        return "\n".join(lines)
    return "\n".join(lines[:begins[0]] + lines[ends[0] + 1:])


ROW_RE = re.compile(r"^\|\s*(\d+)\s*\|\s*\[([A-Za-z][A-Za-z0-9_]*-\d+)\]")


def previous_ranks(description):
    lines, begins, ends = _marker_lines(description)
    if section_state(description) == "none":
        return {}
    out = {}
    for line in lines[begins[0]:ends[0]]:
        m = ROW_RE.match(line.strip())
        if m:
            out.setdefault(m.group(2), int(m.group(1)))
    return out


def cell(text):
    return re.sub(r"\s+", " ", str(text or "")).replace("|", "\\|").strip() or "—"


def _field_cell(current, decision, for_epic):
    """One table cell for Priority or Affected host."""
    current_text = current or "—"
    d = decision or {}
    proposed = d.get("approved_value") or d.get("proposed")
    state = d.get("decision", "unchanged")
    if for_epic:  # the epic records actual values, plus proposals still pending
        if state == "pending" and proposed and proposed != current:
            return f"{current_text} (proposed: {proposed}, pending)"
        return current_text
    if not proposed or proposed == current:
        return f"{current_text} (no change)" + (f"; {d['note']}" if d.get("note") else "")
    return f"{current_text} → {proposed} [{state}]"


def _items(plan):
    return sorted(plan.get("items", []), key=lambda it: it.get("rank", 0))


def _bullets(values, empty="None."):
    values = [v for v in (values or []) if v]
    return "\n".join(f"- {v}" for v in values) if values else empty


def render_section(snap, plan, live=None, result=None):
    """The generated section. `live` (issue id -> issue) gives values as they are now."""
    live = live or {i["idReadable"]: i for i in snap["issues"]}
    short = snap["project"]["shortName"]
    result = result or {}
    rows = []
    for it in _items(plan):
        cur = live.get(it["issue"]) or {}
        blockers = cell(it.get("blockers"))
        ready = it.get("readiness", "")
        readiness = ready if blockers == "—" else f"{ready}: {blockers}"
        if it["issue"] in (result.get("membership_incomplete") or {}):
            readiness += f" (not a child of this epic: {result['membership_incomplete'][it['issue']]})"
        rows.append(
            f"| {it['rank']} | [{it['issue']}]({issue_url(it['issue'])}) {cell(cur.get('summary'))} "
            f"| {_field_cell(cur.get('priority'), it.get('priority'), True)} "
            f"| {_field_cell(cur.get('affected_host'), it.get('affected_host'), True)} "
            f"| {cell(readiness)} | {cell(it.get('reason'))} |")
    nxt = [f"[{i}]({issue_url(i)})" for i in plan.get("next_actionable", [])]
    added, removed = result.get("added", []), result.get("removed", [])
    parts = [
        BEGIN_LINE, "",
        f"## Backlog refinement: {short}", "",
        f"- Project: {short} ({snap['project'].get('name')})",
        f"- Reviewed: {result.get('reviewed_at') or now_stamp()}",
        f"- Eligibility rule: {snap['status_mapping']['rule']}",
        f"- Tickets reviewed: {len(rows)}",
        f"- Children added this run (verified): {len(added)}"
        + (f" ({', '.join(added)})" if added else ""),
        f"- Children removed this run (verified): {len(removed)}"
        + (f" ({', '.join(removed)})" if removed else ""),
        "", "### Ranked backlog", "",
        "| Rank | Issue | Priority | Affected host | Readiness / blockers | Reason |",
        "| --- | --- | --- | --- | --- | --- |", *rows,
        "", "### Next actionable work", "", _bullets(nxt),
        "", "### Cross-project prerequisites", "",
        _bullets(plan.get("cross_project_prerequisites")),
        "", "### Dependency cycles", "", _bullets(plan.get("cycles")),
        "", "### Unresolved questions", "", _bullets(plan.get("questions")),
        "", "### Changes since the previous review", "",
        _bullets(plan.get("changes_since_last"), "First review, or nothing changed."),
        "", END_MARK,
    ]
    return "\n".join(parts)


def review_table(snap, plan, batch_size=25):
    by_id = {i["idReadable"]: i for i in snap["issues"]}
    out, items = [], _items(plan)
    for start in range(0, len(items), batch_size):
        batch = items[start:start + batch_size]
        out.append(f"Batch {start // batch_size + 1}: ranks {batch[0]['rank']}"
                   f"-{batch[-1]['rank']} of {len(items)}")
        out.append("")
        out.append("| Rank | Issue | Current → proposed Priority | Current → proposed "
                   "Affected host | Readiness / blockers | Reason |")
        out.append("| --- | --- | --- | --- | --- | --- |")
        for it in batch:
            cur = by_id.get(it["issue"], {})
            blockers = cell(it.get("blockers"))
            readiness = it.get("readiness", "") if blockers == "—" \
                else f"{it.get('readiness', '')}: {blockers}"
            out.append(
                f"| {it['rank']} | {issue_url(it['issue'])} {cell(cur.get('summary'))} "
                f"| {_field_cell(cur.get('priority'), it.get('priority'), False)} "
                f"| {_field_cell(cur.get('affected_host'), it.get('affected_host'), False)} "
                f"| {cell(readiness)} | {cell(it.get('reason'))} |")
        out.append("")
    conflicts = snap["analysis"]["parent_conflicts"]
    if conflicts:
        out.append("Existing-parent conflicts (each needs a decision: replace or keep):")
        out += [f"- {issue_url(c['issue'])} is already a subtask of {issue_url(c['parent'])}"
                for c in conflicts]
        out.append("")
    out.append(f"Epic: {snap['analysis']['epic_state']} existing match for "
               f"\"{snap['epic_summary']}\"")
    for c in snap["epic_candidates"]:
        out.append(f"- {issue_url(c['idReadable'])} (Type {c['type'] or 'unset'}, "
                   f"Status {c['status'] or 'unset'})")
    return "\n".join(out)


# -------------------------------------------------------------- plan validation

def chosen_epic(snap, plan):
    """The epic candidate the plan names, or None when the plan creates one."""
    epic = plan.get("epic") or {}
    if epic.get("action") != "update":
        return None
    for c in snap["epic_candidates"]:
        if c["idReadable"] == epic.get("idReadable"):
            return c
    return None


def _check_field(problems, issue, label, decision, current, allowed):
    d = decision or {}
    state = d.get("decision", "unchanged")
    if state not in FIELD_DECISIONS:
        problems.append(f"{issue}: {label} decision {state!r} is not one of {FIELD_DECISIONS}")
        return
    for key in ("proposed", "approved_value"):
        value = d.get(key)
        if value is not None and value not in allowed:
            problems.append(f"{issue}: {label} {key} {value!r} is not a live allowed value")
    target = d.get("approved_value") or d.get("proposed")
    if state == "approved":
        if not target:
            problems.append(f"{issue}: {label} is approved but names no value; this skill "
                            "never clears a field")
        if not str(d.get("approval") or "").strip():
            problems.append(f"{issue}: {label} is approved with no approval record")
    if state == "unchanged" and target and target != current:
        problems.append(f"{issue}: {label} is marked unchanged but proposes {target!r} "
                        f"over {current!r}; record approved, rejected or pending")


def plan_edges(snap, plan):
    """Confirmed prerequisite pairs (dependent, prerequisite): links plus the plan's own."""
    pairs = {(d["issue"], d["depends_on"]) for d in snap["analysis"]["dependencies"]}
    for it in plan.get("items", []):
        for pre in it.get("after") or []:
            pairs.add((it["issue"], pre))
    return sorted(pairs)


def validate_plan(snap, plan):
    """Every reason this plan must not be applied. An empty list means it may be."""
    problems = []
    short = snap["project"]["shortName"]
    if plan.get("project") != short:
        problems.append(f"plan is for {plan.get('project')!r}, snapshot is for {short!r}")
    if plan.get("snapshot_collected_at") != snap["collected_at"]:
        problems.append("plan was not made from this snapshot (snapshot_collected_at differs)")
    by_id = {i["idReadable"]: i for i in snap["issues"]}
    eligible = set(snap["analysis"]["eligible"])
    items = plan.get("items", [])
    seen = [it.get("issue") for it in items]
    for missing in sorted(eligible - set(seen), key=issue_number):
        problems.append(f"{missing}: eligible but has no rank")
    for extra in sorted(set(seen) - eligible, key=lambda s: issue_number(s or "")):
        problems.append(f"{extra}: ranked but not an eligible ticket of {short}")
    for dup in sorted({s for s in seen if seen.count(s) > 1}):
        problems.append(f"{dup}: ranked more than once")
    ranks = sorted(it.get("rank") for it in items if isinstance(it.get("rank"), int))
    if ranks != list(range(1, len(items) + 1)):
        problems.append(f"ranks must be 1..{len(items)} with no gap or tie")

    hosts = snap["bundles"]["affected_host"]
    priorities = [p for p in snap["bundles"]["priority"] if p in ALLOWED_PRIORITIES]
    conflicts = {c["issue"] for c in snap["analysis"]["parent_conflicts"]}
    rank = {it.get("issue"): it.get("rank") for it in items}
    for it in items:
        issue = it.get("issue")
        cur = by_id.get(issue)
        if not cur:
            continue
        if it.get("readiness") not in READINESS:
            problems.append(f"{issue}: readiness must be one of {READINESS}")
        if not str(it.get("reason") or "").strip():
            problems.append(f"{issue}: no reason recorded")
        _check_field(problems, issue, "Priority", it.get("priority"), cur["priority"], priorities)
        _check_field(problems, issue, "Affected host", it.get("affected_host"),
                     cur["affected_host"], hosts)
        parent = (it.get("parent") or {}).get("decision")
        if issue in conflicts:
            if parent not in ("replace", "keep"):
                problems.append(f"{issue}: already has parent {cur['parent']['idReadable']}; "
                                "the plan must record replace or keep")
            elif parent == "replace" and not str(it["parent"].get("approval") or "").strip():
                problems.append(f"{issue}: replacing its parent has no approval record")

    cyclic = {m for comp in find_cycles(plan_edges(snap, plan)) for m in comp}
    for dependent, pre in plan_edges(snap, plan):
        if dependent in cyclic and pre in cyclic:
            continue
        if dependent in rank and pre in rank and not rank[pre] < rank[dependent]:
            problems.append(f"{dependent} is ranked before its prerequisite {pre}")
    for member in sorted(cyclic & set(rank), key=issue_number):
        it = next(i for i in items if i["issue"] == member)
        if it.get("readiness") != "needs-clarification":
            problems.append(f"{member}: in a dependency cycle, so its readiness must be "
                            "needs-clarification rather than an invented order")

    problems += _validate_epic(snap, plan)
    return problems


def _validate_epic(snap, plan):
    problems = []
    epic = plan.get("epic") or {}
    cands = snap["epic_candidates"]
    mapping = snap["status_mapping"]
    if not cands:
        if epic.get("action") != "create":
            problems.append("no epic exists; the plan must say epic.action = create")
        elif epic.get("status") not in snap["bundles"]["status"] \
                or epic.get("status") in mapping["excluded"]:
            problems.append("epic.status must be a live, open Status value for the new epic")
        elif not str(epic.get("approval") or "").strip():
            problems.append("creating the epic has no approval record")
        if EPIC_TYPE not in snap["bundles"]["type"]:
            problems.append(f"this project has no Type value {EPIC_TYPE!r}")
        return problems
    chosen = chosen_epic(snap, plan)
    if not chosen:
        names = ", ".join(c["idReadable"] for c in cands)
        problems.append(f"the plan must say epic.action = update and name one of: {names}")
        return problems
    if len(cands) > 1 and not str(epic.get("canonical_approval") or "").strip():
        problems.append(f"{len(cands)} issues are named {snap['epic_summary']}; choosing "
                        f"{chosen['idReadable']} has no approval record")
    if isinstance(chosen.get("section"), str) and chosen["section"].startswith("malformed"):
        problems.append(f"{chosen['idReadable']}: {chosen['section']}")
    if chosen["children"] is None:
        problems.append(f"{chosen['idReadable']}: its children could not be read")
    fixes = epic.get("corrections") or {}
    if chosen["type"] != EPIC_TYPE and not str((fixes.get("type") or {}).get("approval") or "").strip():
        problems.append(f"{chosen['idReadable']} has Type {chosen['type']!r}, not Epic; "
                        "the correction needs an approval record")
    if chosen["status_class"] != "open":
        fix = fixes.get("status") or {}
        if fix.get("to") not in snap["bundles"]["status"] or fix.get("to") in mapping["excluded"] \
                or not str(fix.get("approval") or "").strip():
            problems.append(f"{chosen['idReadable']} has Status {chosen['status']!r}; reopening "
                            "it needs an approved, open Status value")
    removals = {r.get("issue"): r for r in plan.get("membership_removals") or []}
    for child in chosen["children"] or []:
        if child["project"] != snap["project"]["shortName"] and child["idReadable"] not in removals:
            problems.append(f"{child['idReadable']} is a child of the epic but belongs to "
                            f"{child['project']}; record a membership_removals decision")
    return problems


# ----------------------------------------------------------------------- apply

class Journal:
    """Append-only record of what apply did. A record of intent and outcome,
    never proof: whether a write landed is always decided by reading live state."""

    def __init__(self, path, dry_run=False):
        self.path, self.dry_run, self.entries = path, dry_run, []
        if path and not dry_run:
            os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)

    def record(self, op, target, outcome, **detail):
        entry = {"at": now_stamp(), "op": op, "target": target, "outcome": outcome, **detail}
        self.entries.append(entry)
        if self.path and not self.dry_run:
            with open(self.path, "a", encoding="utf-8") as fh:
                fh.write(json.dumps(entry, sort_keys=True) + "\n")
        return outcome


def guarded_write(journal, op, target, is_done, do, **detail):
    """Write once and prove it by reading back.

    is_done() reads live state. It runs before the write (so nothing already in
    place is written again) and after it, whatever the response was: an error or
    a timeout does not mean the write failed, and a 200 does not mean it landed.
    """
    if is_done():
        return journal.record(op, target, "already-in-place", **detail)
    if journal.dry_run:
        return journal.record(op, target, "would-apply", **detail)
    error = None
    try:
        do()
    except Fail as exc:
        error = str(exc)
    try:
        landed = is_done()
    except Fail as exc:
        return journal.record(op, target, "unverified", error=error, read_error=str(exc), **detail)
    if landed:
        return journal.record(op, target, "applied-verified" if not error
                              else "applied-verified-after-error", error=error, **detail)
    return journal.record(op, target, "failed", error=error or "read-back does not match",
                          **detail)


OK_OUTCOMES = ("already-in-place", "applied-verified", "applied-verified-after-error",
               "would-apply")


def read_issue_fields(issue_id):
    return api("GET", f"/api/issues/{issue_id}", {"fields": LIST_FIELDS})


def set_field(issue_id, key, value):
    live = read_issue_fields(issue_id)
    fld = field_map(live).get(key)
    if not fld:
        raise Fail(f"{live.get('idReadable')} has no {FIELDS[key][0]} field")
    api("POST", f"/api/issues/{issue_id}", {"fields": "id"},
        {"customFields": [{"id": fld["id"], "$type": fld["$type"], "value": {"name": value}}]})


def compute_drift(snap, live_snap, plan):
    """What changed since the review. Per-issue drift stops that issue's own
    operations; any drift at all stops the epic description being rewritten."""
    before = {i["idReadable"]: i for i in snap["issues"]}
    after = {i["idReadable"]: i for i in live_snap["issues"]}
    per_issue, general = {}, []
    for rid in sorted(set(before) | set(after), key=issue_number):
        b, a = before.get(rid), after.get(rid)
        notes = []
        if b and not a:
            if b["eligible"]:
                notes.append("no longer in the project")
        elif a and not b:
            if a["eligible"]:
                notes.append("new eligible ticket, not reviewed")
        else:
            for key, label in (("status", "Status"), ("priority", "Priority"),
                               ("affected_host", "Affected host")):
                if b[key] != a[key] and (b["eligible"] or a["eligible"]):
                    notes.append(f"{label} changed {b[key]!r} -> {a[key]!r}")
            bp, ap = (b["parent"] or {}).get("id"), (a["parent"] or {}).get("id")
            if bp != ap and (b["eligible"] or a["eligible"]):
                notes.append("parent changed")
        if notes:
            per_issue[rid] = notes
    b_epics = sorted((c["idReadable"], c["type"], c["status"]) for c in snap["epic_candidates"])
    a_epics = sorted((c["idReadable"], c["type"], c["status"])
                     for c in live_snap["epic_candidates"])
    if b_epics != a_epics:
        general.append(f"epic candidates changed: {b_epics} -> {a_epics}")
    return {"issues": per_issue, "epic": general}


def find_epics(short):
    raw, _ = read_project_issues(short)
    return [r for r in raw if (r.get("summary") or "") == f"{short}{EPIC_SUFFIX}"]


def create_epic(snap, plan, journal):
    """Create the epic only when live state shows none. Returns its entity id or None."""
    short = snap["project"]["shortName"]
    summary = snap["epic_summary"]
    existing = find_epics(short)
    if existing:  # someone, or an earlier attempt, created it since the review
        journal.record("create-epic", summary, "blocked",
                       error=f"{len(existing)} issue(s) with this summary now exist; replan")
        return None
    if journal.dry_run:
        journal.record("create-epic", summary, "would-apply")
        return None
    sample = read_issue_fields(next(i["id"] for i in snap["issues"]))
    fmap = field_map(sample)
    epic = plan["epic"]
    wanted = {"status": {"name": epic["status"]}, "type": {"name": EPIC_TYPE},
              "date_entered": int(time.time() * 1000)}
    if epic.get("assignee"):
        wanted["assignee"] = {"login": epic["assignee"]}
    fields = []
    for key, value in wanted.items():
        if key not in fmap:
            raise Fail(f"{short} has no {FIELDS[key][0]} field to set on the new epic")
        fields.append({"id": fmap[key]["id"], "$type": fmap[key]["$type"], "value": value})
    error = None
    try:
        api("POST", "/api/issues", {"fields": "id,idReadable"},
            {"project": {"id": snap["project"]["id"]}, "summary": summary,
             "customFields": fields})
    except Fail as exc:
        error = str(exc)
    # Never assume a failed response means nothing was created: look.
    found = find_epics(short)
    if not found and error:
        time.sleep(2)
        found = find_epics(short)
    if len(found) == 1:
        journal.record("create-epic", found[0]["idReadable"],
                       "applied-verified" if not error else "applied-verified-after-error",
                       error=error)
        return found[0]["id"]
    journal.record("create-epic", summary, "failed",
                   error=error or f"{len(found)} issues with this summary after the create")
    return None


def ancestors(issue_id, limit=50):
    out, current = [], issue_id
    for _ in range(limit):
        parent = parent_of(api("GET", f"/api/issues/{current}", {"fields": "parent(issues(id))"}))
        if not parent or parent["id"] in out:
            return out
        out.append(parent["id"])
        current = parent["id"]
    raise Fail("parent chain is deeper than expected; refusing to guess about cycles")


def live_parent_id(issue_id):
    parent = parent_of(api("GET", f"/api/issues/{issue_id}", {"fields": "parent(issues(id))"}))
    return parent["id"] if parent else None


def apply(snap, plan, journal_path, dry_run=False):
    problems = validate_plan(snap, plan)
    if problems:
        raise Fail("the plan is not valid, nothing was written:\n  " + "\n  ".join(problems))
    journal = Journal(journal_path, dry_run)
    short = snap["project"]["shortName"]
    project = {"id": snap["project"]["id"], "shortName": short, "name": snap["project"]["name"]}

    # Recheck before writing: the review is only as good as the state it saw.
    live_snap = collect(project, deep=False)
    drift = compute_drift(snap, live_snap, plan)
    live = {i["idReadable"]: i for i in live_snap["issues"]}
    stale = drift["issues"]
    epic_blocked = list(drift["epic"])
    result = {"field_changes": [], "added": [], "removed": [], "membership_incomplete": {},
              "skipped": [], "reviewed_at": now_stamp()}

    # 1. Field changes: approved ones only, and only where nothing moved.
    for it in _items(plan):
        rid = it["issue"]
        for key, label in (("priority", "Priority"), ("affected_host", "Affected host")):
            d = it.get(key) or {}
            if d.get("decision") != "approved":
                continue
            target = d.get("approved_value") or d.get("proposed")
            if rid in stale:
                journal.record("set-field", rid, "skipped-stale", field=label,
                               reason="; ".join(stale[rid]))
                result["skipped"].append(f"{rid} {label}: changed since review")
                continue
            entity = live[rid]["id"]
            outcome = guarded_write(
                journal, "set-field", rid,
                lambda e=entity, k=key, t=target: field_value(read_issue_fields(e), k) == t,
                lambda e=entity, k=key, t=target: set_field(e, k, t),
                field=label, value=target, approval=d.get("approval"))
            if outcome in ("applied-verified", "applied-verified-after-error", "would-apply"):
                result["field_changes"].append(f"{rid} {label} -> {target}")

    # 2. The epic itself.
    epic_id = None
    epic_plan = plan["epic"]
    if not epic_blocked:
        if epic_plan["action"] == "create":
            epic_id = create_epic(snap, plan, journal)
            if not epic_id and not dry_run:
                epic_blocked.append("the epic could not be created or confirmed")
        else:
            chosen = chosen_epic(snap, plan)
            epic_id = chosen["id"]
            fixes = epic_plan.get("corrections") or {}
            if chosen["type"] != EPIC_TYPE:
                outcome = guarded_write(
                    journal, "set-field", chosen["idReadable"],
                    lambda: field_value(read_issue_fields(epic_id), "type") == EPIC_TYPE,
                    lambda: set_field(epic_id, "type", EPIC_TYPE), field="Type", value=EPIC_TYPE)
                if outcome not in OK_OUTCOMES:
                    epic_blocked.append("the epic's Type could not be corrected")
            if chosen["status_class"] != "open":
                to = fixes["status"]["to"]
                outcome = guarded_write(
                    journal, "set-field", chosen["idReadable"],
                    lambda: field_value(read_issue_fields(epic_id), "status") == to,
                    lambda: set_field(epic_id, "status", to), field="Status", value=to)
                if outcome not in OK_OUTCOMES:
                    epic_blocked.append("the epic's Status could not be corrected")

    # 3. Membership.
    if epic_id and not epic_blocked:
        types = link_types()
        link_id = subtask_link_id(epic_id, types)
        epic_ancestors = ancestors(epic_id)
        children = read_children(epic_id, types, live_snap["status_mapping"])
        removals = {r["issue"]: r for r in plan.get("membership_removals") or []}
        for child in children:
            cid, rid = child["id"], child["idReadable"]
            foreign = child["project"] != short
            if foreign:
                if (removals.get(rid) or {}).get("decision") != "approved":
                    result["skipped"].append(f"{rid}: cross-project child left in place, "
                                             "removal not approved")
                    continue
            elif child["status_class"] not in ("done", "do-not-do"):
                continue  # still open, or Status unreadable: keep it and say so elsewhere
            outcome = guarded_write(
                journal, "remove-child", rid,
                lambda c=cid: live_parent_id(c) != epic_id,
                lambda c=cid: api("DELETE", f"/api/issues/{epic_id}/links/{link_id}/issues/{c}"),
                reason="cross-project" if foreign else child["status"])
            if outcome in ("applied-verified", "applied-verified-after-error", "would-apply"):
                result["removed"].append(rid)
        for it in _items(plan):
            rid = it["issue"]
            if rid in stale:
                journal.record("add-child", rid, "skipped-stale", reason="; ".join(stale[rid]))
                result["membership_incomplete"][rid] = "changed since review"
                continue
            cur = live[rid]
            if cur["id"] == epic_id or cur["id"] in epic_ancestors:
                journal.record("add-child", rid, "blocked", reason="would create a hierarchy cycle")
                result["membership_incomplete"][rid] = "would create a hierarchy cycle"
                continue
            parent = cur["parent"]
            if parent and parent["id"] != epic_id \
                    and (it.get("parent") or {}).get("decision") != "replace":
                journal.record("add-child", rid, "skipped-not-approved",
                               reason=f"existing parent {parent['idReadable']} kept")
                result["membership_incomplete"][rid] = f"existing parent {parent['idReadable']}"
                continue
            outcome = guarded_write(
                journal, "add-child", rid,
                lambda c=cur["id"]: live_parent_id(c) == epic_id,
                lambda c=cur["id"]: api("POST", f"/api/issues/{epic_id}/links/{link_id}/issues",
                                        {"fields": "id"}, {"id": c}))
            if outcome in ("applied-verified", "applied-verified-after-error", "would-apply"):
                result["added"].append(rid)
            elif outcome != "already-in-place":
                result["membership_incomplete"][rid] = "link write failed"
    elif dry_run and not epic_blocked:
        # The epic does not exist yet, so list what a real run would link to it.
        for it in _items(plan):
            rid = it["issue"]
            parent = live[rid]["parent"] if rid in live else None
            if rid in stale:
                result["membership_incomplete"][rid] = "changed since review"
            elif parent and (it.get("parent") or {}).get("decision") != "replace":
                result["membership_incomplete"][rid] = f"existing parent {parent['idReadable']}"
            else:
                journal.record("add-child", rid, "would-apply")
                result["added"].append(rid)
    else:
        for it in _items(plan):
            result["membership_incomplete"].setdefault(it["issue"], "epic operations blocked")

    # 4. The description: only when the ranked list still describes what is there.
    description_state = "not-written"
    if stale or epic_blocked:
        why = "; ".join(epic_blocked) or "tickets changed since review"
        journal.record("write-description", snap["epic_summary"], "blocked", reason=why)
        description_state = f"blocked: {why}"
    elif epic_id:
        fresh = collect(project, deep=False)
        now_live = {i["idReadable"]: i for i in fresh["issues"]}
        section = render_section(snap, plan, now_live, result)
        current = read_issue_fields(epic_id).get("description") or ""
        wanted = splice_section(current, section)  # raises on malformed markers
        if outside_section(wanted) != outside_section(current):
            raise Fail("refusing to write: text outside the generated section would change")
        outcome = guarded_write(
            journal, "write-description", snap["epic_summary"],
            lambda: (read_issue_fields(epic_id).get("description") or "").replace("\r\n", "\n")
            == wanted,
            lambda: api("POST", f"/api/issues/{epic_id}", {"fields": "id"},
                        {"description": wanted}))
        description_state = outcome
    elif dry_run:
        description_state = journal.record("write-description", snap["epic_summary"], "would-apply")

    failures = [e for e in journal.entries if e["outcome"] in ("failed", "unverified")]
    epic_readable = None
    if epic_id:
        epic_readable = read_issue_fields(epic_id).get("idReadable")
    report = {
        "project": short, "dry_run": dry_run,
        "epic": epic_readable, "epic_url": issue_url(epic_readable) if epic_readable else None,
        "reviewed": len(plan["items"]), "next_actionable": plan.get("next_actionable", []),
        "field_changes": result["field_changes"], "children_added": result["added"],
        "children_removed": result["removed"],
        "membership_incomplete": result["membership_incomplete"],
        "description": description_state,
        "drift": drift, "epic_blocked": epic_blocked, "skipped": result["skipped"],
        "failures": failures, "journal": journal_path,
        "pending_decisions": [f"{it['issue']} {label}"
                              for it in _items(plan)
                              for key, label in (("priority", "Priority"),
                                                 ("affected_host", "Affected host"))
                              if (it.get(key) or {}).get("decision") == "pending"],
    }
    report["complete"] = not (failures or stale or epic_blocked
                              or result["membership_incomplete"])
    return report


# ------------------------------------------------------------------ read-issue

def read_issue(readable):
    raw = api("GET", f"/api/issues/{readable}", {"fields": LIST_FIELDS})
    out = {"id": raw["id"], "idReadable": raw["idReadable"], "url": issue_url(raw["idReadable"]),
           "project": (raw.get("project") or {}).get("shortName"),
           "summary": raw.get("summary"), "description": raw.get("description") or "",
           "status": field_value(raw, "status"), "priority": field_value(raw, "priority"),
           "affected_host": field_value(raw, "affected_host"), "parent": parent_of(raw)}
    out["links"] = read_links(raw["id"])
    out["comments"] = read_comments(raw["id"])
    return out


# ------------------------------------------------------------------------- CLI

def _load(path):
    with open(os.path.expanduser(path), encoding="utf-8") as fh:
        return json.load(fh)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("resolve-project").add_argument("project")
    p = sub.add_parser("collect")
    p.add_argument("project"); p.add_argument("out")
    sub.add_parser("read-issue").add_argument("issue")
    for name in ("validate-plan", "render-section"):
        p = sub.add_parser(name)
        p.add_argument("snapshot"); p.add_argument("plan")
    p = sub.add_parser("review-table")
    p.add_argument("snapshot"); p.add_argument("plan")
    p.add_argument("--batch-size", type=int, default=25)
    p = sub.add_parser("apply")
    p.add_argument("snapshot"); p.add_argument("plan")
    p.add_argument("--journal", required=True, help="append-only record of this apply")
    p.add_argument("--dry-run", action="store_true", help="list the operations, write nothing")
    args = ap.parse_args(argv)

    try:
        if args.cmd == "resolve-project":
            print(json.dumps(resolve_project(args.project), indent=2))
        elif args.cmd == "collect":
            snap = collect(resolve_project(args.project))
            out = os.path.expanduser(args.out)
            os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
            with open(out, "w", encoding="utf-8") as fh:
                json.dump(snap, fh, indent=2, sort_keys=True)
            print(f"Wrote {out}")
            print(json.dumps({k: snap["analysis"][k] for k in
                              ("counts", "status_unknown", "cycles", "parent_conflicts",
                               "epic_state", "incomplete_reads")}, indent=2))
            print(f"Eligibility: {snap['status_mapping']['rule']}")
        elif args.cmd == "read-issue":
            print(json.dumps(read_issue(args.issue.strip().rsplit("/", 1)[-1]), indent=2))
        elif args.cmd == "validate-plan":
            problems = validate_plan(_load(args.snapshot), _load(args.plan))
            for prob in problems:
                print(f"FAIL: {prob}")
            if problems:
                return 1
            print("OK: the plan covers every eligible ticket and every write has an approval")
        elif args.cmd == "review-table":
            print(review_table(_load(args.snapshot), _load(args.plan), args.batch_size))
        elif args.cmd == "render-section":
            print(render_section(_load(args.snapshot), _load(args.plan)))
        elif args.cmd == "apply":
            report = apply(_load(args.snapshot), _load(args.plan),
                           os.path.expanduser(args.journal), args.dry_run)
            print(json.dumps(report, indent=2))
            return 0 if report["complete"] else 3
    except Fail as exc:
        sys.stdout.flush()
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
